### ISSUE TITLE
AUTH_UNAUTHROIZED -  Your account does not have access to this endpoint

### ISSUE THREAD

**Issue by 2088669827** [MrChebur/usgs-machine-to-machine-API#1]
When I go to the "downloadOptions" function ,its response is "AUTH_UNAUTHROIZED -  Your account does not have access to this endpoint".But I can successfully run "login" and "searchDataset".What can I do to solve the problem?

**Comment by MrChebur** [comment]
@2088669827  Do you have machine-to-machine access?

**Comment by 2088669827** [comment]
No,but I request it just now at https://ers.cr.usgs.gov/profile/access ,is it right?
If right, how long it cost for me to be permitted to have it?

**Comment by MrChebur** [comment]
> 
> 
> No,but I request it just now at https://ers.cr.usgs.gov/profile/access,is it right?
> If right, how long it cost for me to be permitted to have it?

It's free. After gaining access, try this test code:
https://raw.githubusercontent.com/MrChebur/usgs-machine-to-machine-API/master/UsageExample.py
If everything is ok, 1 quicklook should be loaded.

**Comment by 2088669827** [comment]
Thank you very much!

**Comment by MrChebur** [comment]
You are welcome! Closed. =)
