### ISSUE TITLE
Help downloading surface reflectance NDVI 

### ISSUE THREAD

**Issue by henrykironde** [MrChebur/usgs-machine-to-machine-API#5]
@MrChebur we are trying to download NDVI data from ROI below. Could you help us because we couldn't get to understand how to deal with the API. 

```Python
    ROIf = [[
    [35.3331, -107.8033 ],
    [35.3331,  -110.9702],
    [33.6878,   -110.9702],
    [33.6878,  -107.8033],
    ]]
```

Also for the  API (v1.5.0), could you probably provide more details about the available options for the parameter. 
For example the `datasetName` or `filterType`.  I was expecting to use the EarthExplore to search for the data and get these details but that seems to provide no help.

**Comment by MrChebur** [comment]
1. Swap the coordinates.
2. The polygon is not closed (add the first coordinate to the end).

Correct ROI:
```
ROI = [[
	[-107.8033, 35.3331],
	[-110.9702, 35.3331],
	[-110.9702, 33.6878],
	[-107.8033, 33.6878],
	[-107.8033, 35.3331],
]]
```

About the documentation:
This API is a simple wrapper. You should read the USGS documentation to understand how to use it:

Main page:
https://m2m.cr.usgs.gov/api/docs/json/

Datatypes:
https://m2m.cr.usgs.gov/api/docs/datatypes/

USGS API:
https://m2m.cr.usgs.gov/api/docs/reference/

Check the `dataset-search` method in the USGS docs:

> This method is used to find datasets available for searching. **By passing only API Key, all available datasets are returned**. Additional parameters such as temporal range and spatial bounding box can be used to find datasets that provide more specific data. The dataset name parameter can be used to limit the results based on matching the supplied value against the public dataset name with assumed wildcards at the beginning and end.

**Comment by MrChebur** [comment]
Check the `dataset-search` method in the USGS docs.

> This method is used to find datasets available for searching. By passing only API Key, all available datasets are returned. Additional parameters such as temporal range and spatial bounding box can be used to find datasets that provide more specific data. The dataset name parameter can be used to limit the results based on matching the supplied value against the public dataset name with assumed wildcards at the beginning and end.
